fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.6.0
    file_concat: git://github.com/electrical/puppet-lib-file_concat.git
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 1.8.0
  symlinks:
    logstash: "#{source_dir}"
