name    'elasticsearch-logstash'
version '0.4.3-opentable1'
source 'https://github.com/opentable/puppet-logstash'
author 'elasticsearch'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Logstash'
description 'Module for managing and configuring Logstash'
project_page 'https://github.com/elasticsearch/puppet-logstash'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'electrical/file_concat', '>= 1.0.0'
